ToyotaResponseDynamoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-rt-toyota-response-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "loadId"
        AttributeType: "S"
      - AttributeName: "SeqNo"
        AttributeType: "S"
      - AttributeName: "InsertedTimeStamp"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "loadId"
        KeyType: HASH
      - AttributeName: "SeqNo"
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: omni-toyota-response-InsertedTimeStamp-index-${self:provider.stage}
        KeySchema:
          - AttributeName: "InsertedTimeStamp"
            KeyType: "HASH"
