ToyotaResponseDynamoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-rt-toyota-response-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "loadId"
        AttributeType: "S"
      - AttributeName: "SeqNo"
        AttributeType: "S"
      - AttributeName: "ConciliationTimeStamp"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "loadId"
        KeyType: HASH
      - AttributeName: "SeqNo"
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: toyota-reconciliation-report-ConciliationTimeStamp-Index-${self:provider.stage}
        KeySchema:
          - AttributeName: "ConciliationTimeStamp"
            KeyType: "HASH"
        Projection:
          ProjectionType: "ALL"
