ToyotaDynamoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-rt-toyota-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "loadId"
        AttributeType: "S"
      - AttributeName: "SeqNo"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "loadId"
        KeyType: HASH
      - AttributeName: "SeqNo"
        KeyType: RANGE
    # ProvisionedThroughput:
    #   ReadCapacityUnits: 5
    #   WriteCapacityUnits: 5
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
