ToyotaReconReport:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-rt-toyota-recon-report-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "PK"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "PK"
        KeyType: HASH
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
