---
function:
  name: omni-toyota-reconciliation-report-${self:provider.stage}
  handler: src/reconciliationReport.handler
  layers:
    - { Ref: OmniToyotaLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/reconciliationReport.js"
      - "src/shared/**"
  events:
    - schedule:
        rate: cron(0 1 * * ? *) # CST:- 08:00 PM ,  IST:- 6:30 am
  logSubscription: true
  environment:
    TOYOTA_DDB: ${ssm:/omni-rt-toyota/${self:provider.stage}/ddb.tableName~true}
    TOYOTA_CLIENT_ID: ${ssm:/omni-rt-toyota/${self:provider.stage}/authApi.clientId~true}
    TOYOTA_JWT_URL: ${ssm:/omni-rt-toyota/${self:provider.stage}/authApi.url~true}
    TOYOTA_URL: ${ssm:/omni-rt-toyota/${self:provider.stage}/toyotaApi.url~true}
    TOYOTA_RESPONSE_DDB: ${ssm:/omni-rt-toyota/${self:provider.stage}/response/ddb.tableName~true}
    TOYOTA_RECON_REPORT_DDB: ${ssm:/omni-rt-toyota/${self:provider.stage}/reconResponse/ddb.tableName~true}
    STAGE: ${self:custom.stage}
