---
function:
  name: omni-toyota-updates-${self:provider.stage}
  handler: src/toyotaUpdates.handler
  # provisionedConcurrency: 1
  # concurrencyAutoscaling: true
  layers:
    - { Ref: OmniToyotaLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/toyotaUpdates.js"
      - "src/shared/**"
  events:
    # - stream: ${ssm:/omni-rt-toyota/${self:provider.stage}/ddb.streamArn~true}
  environment:
    # DYNAMO_DB_TABLE: ${ssm:/omni-rt-toyota/${self:provider.stage}/apar-failure/ddb.tableName~true}
